dataset:
  source:
    path: '/home/initial/workspace/misc/mt/ultralytics/preprocess/vott'
    img_cat: images
    anno_cat: annotations
  destination:
    path: '/home/initial/workspace/misc/mt/ultralytics/preprocess/coco'
    img_cat: images
    anno_file: annotations.json

info:
  year: 2020 
  version: v1 
  description: UAVVaste dataset 
  contributor: None
  url: https://uavvaste.ithub.io/
